var otherLocations = [
   {
      "name":"Alberta",
      "records":[
         {
            "name":"calgary",
            "url":"http://calgary.craigslist.ca"
         },
         {
            "name":"edmonton",
            "url":"http://edmonton.craigslist.ca"
         },
         {
            "name":"ft mcmurray",
            "url":"http://ftmcmurray.craigslist.ca"
         },
         {
            "name":"lethbridge",
            "url":"http://lethbridge.craigslist.ca"
         },
         {
            "name":"medicine hat",
            "url":"http://hat.craigslist.ca"
         },
         {
            "name":"peace river country",
            "url":"http://peace.craigslist.ca"
         },
         {
            "name":"red deer",
            "url":"http://reddeer.craigslist.ca"
         }
      ]
   },
   {
      "name":"British Columbia",
      "records":[
         {
            "name":"cariboo",
            "url":"http://cariboo.craigslist.ca"
         },
         {
            "name":"comox valley",
            "url":"http://comoxvalley.craigslist.ca"
         },
         {
            "name":"fraser valley",
            "url":"http://abbotsford.craigslist.ca"
         },
         {
            "name":"kamloops",
            "url":"http://kamloops.craigslist.ca"
         },
         {
            "name":"kelowna / okanagan",
            "url":"http://kelowna.craigslist.ca"
         },
         {
            "name":"kootenays",
            "url":"http://cranbrook.craigslist.ca"
         },
         {
            "name":"nanaimo",
            "url":"http://nanaimo.craigslist.ca"
         },
         {
            "name":"prince george",
            "url":"http://princegeorge.craigslist.ca"
         },
         {
            "name":"skeena-bulkley",
            "url":"http://skeena.craigslist.ca"
         },
         {
            "name":"sunshine coast",
            "url":"http://sunshine.craigslist.ca"
         },
         {
            "name":"vancouver",
            "url":"http://vancouver.craigslist.ca"
         },
         {
            "name":"victoria",
            "url":"http://victoria.craigslist.ca"
         },
         {
            "name":"whistler",
            "url":"http://whistler.craigslist.ca"
         }
      ]
   },
   {
      "name":"Manitoba",
      "records":[
         {
            "name":"winnipeg",
            "url":"http://winnipeg.craigslist.ca"
         }
      ]
   },
   {
      "name":"New Brunswick",
      "records":[
         {
            "name":"new brunswick",
            "url":"http://newbrunswick.craigslist.ca"
         }
      ]
   },
   {
      "name":"Newfoundland and Labrador",
      "records":[
         {
            "name":"st john's",
            "url":"http://newfoundland.craigslist.ca"
         }
      ]
   },
   {
      "name":"Northwest Territories",
      "records":[
         {
            "name":"territories",
            "url":"http://territories.craigslist.ca"
         },
         {
            "name":"yellowknife",
            "url":"http://yellowknife.craigslist.ca"
         }
      ]
   },
   {
      "name":"Nova Scotia",
      "records":[
         {
            "name":"halifax",
            "url":"http://halifax.craigslist.ca"
         }
      ]
   },
   {
      "name":"Ontario",
      "records":[
         {
            "name":"barrie",
            "url":"http://barrie.craigslist.ca"
         },
         {
            "name":"belleville",
            "url":"http://belleville.craigslist.ca"
         },
         {
            "name":"brantford-woodstock",
            "url":"http://brantford.craigslist.ca"
         },
         {
            "name":"chatham-kent",
            "url":"http://chatham.craigslist.ca"
         },
         {
            "name":"cornwall",
            "url":"http://cornwall.craigslist.ca"
         },
         {
            "name":"guelph",
            "url":"http://guelph.craigslist.ca"
         },
         {
            "name":"hamilton-burlington",
            "url":"http://hamilton.craigslist.ca"
         },
         {
            "name":"kingston",
            "url":"http://kingston.craigslist.ca"
         },
         {
            "name":"kitchener-waterloo-cambridge",
            "url":"http://kitchener.craigslist.ca"
         },
         {
            "name":"london ",
            "url":"http://londonon.craigslist.ca"
         },
         {
            "name":"niagara region",
            "url":"http://niagara.craigslist.ca"
         },
         {
            "name":"ottawa-hull-gatineau",
            "url":"http://ottawa.craigslist.ca"
         },
         {
            "name":"owen sound",
            "url":"http://owensound.craigslist.ca"
         },
         {
            "name":"peterborough",
            "url":"http://peterborough.craigslist.ca"
         },
         {
            "name":"sarnia",
            "url":"http://sarnia.craigslist.ca"
         },
         {
            "name":"sault ste marie",
            "url":"http://soo.craigslist.ca"
         },
         {
            "name":"sudbury",
            "url":"http://sudbury.craigslist.ca"
         },
         {
            "name":"thunder bay",
            "url":"http://thunderbay.craigslist.ca"
         },
         {
            "name":"toronto",
            "url":"http://toronto.craigslist.ca"
         },
         {
            "name":"windsor",
            "url":"http://windsor.craigslist.ca"
         }
      ]
   },
   {
      "name":"Prince Edward Island",
      "records":[
         {
            "name":"prince edward island",
            "url":"http://pei.craigslist.ca"
         }
      ]
   },
   {
      "name":"Quebec",
      "records":[
         {
            "name":"montreal",
            "url":"http://montreal.craigslist.ca"
         },
         {
            "name":"quebec city",
            "url":"http://quebec.craigslist.ca"
         },
         {
            "name":"saguenay",
            "url":"http://saguenay.craigslist.ca"
         },
         {
            "name":"sherbrooke",
            "url":"http://sherbrooke.craigslist.ca"
         },
         {
            "name":"trois-rivieres",
            "url":"http://troisrivieres.craigslist.ca"
         }
      ]
   },
   {
      "name":"Saskatchewan",
      "records":[
         {
            "name":"regina",
            "url":"http://regina.craigslist.ca"
         },
         {
            "name":"saskatoon",
            "url":"http://saskatoon.craigslist.ca"
         }
      ]
   },
   {
      "name":"Yukon Territory",
      "records":[
         {
            "name":"whitehorse",
            "url":"http://whitehorse.craigslist.ca"
         }
      ]
   },
   {
      "name":"Austria",
      "records":[
         {
            "name":"vienna",
            "url":"http://vienna.craigslist.at"
         }
      ]
   },
   {
      "name":"Belgium",
      "records":[
         {
            "name":"belgium",
            "url":"http://brussels.craigslist.org"
         }
      ]
   },
   {
      "name":"Bulgaria",
      "records":[
         {
            "name":"bulgaria",
            "url":"http://bulgaria.craigslist.org"
         }
      ]
   },
   {
      "name":"Croatia",
      "records":[
         {
            "name":"croatia",
            "url":"http://zagreb.craigslist.org"
         }
      ]
   },
   {
      "name":"Czech Republic",
      "records":[
         {
            "name":"prague",
            "url":"http://prague.craigslist.cz"
         }
      ]
   },
   {
      "name":"Denmark",
      "records":[
         {
            "name":"copenhagen",
            "url":"http://copenhagen.craigslist.org"
         }
      ]
   },
   {
      "name":"Finland",
      "records":[
         {
            "name":"finland",
            "url":"http://helsinki.craigslist.fi"
         }
      ]
   },
   {
      "name":"France",
      "records":[
         {
            "name":"bordeaux",
            "url":"http://bordeaux.craigslist.org"
         },
         {
            "name":"brittany",
            "url":"http://rennes.craigslist.org"
         },
         {
            "name":"grenoble",
            "url":"http://grenoble.craigslist.org"
         },
         {
            "name":"lille",
            "url":"http://lille.craigslist.org"
         },
         {
            "name":"loire valley",
            "url":"http://loire.craigslist.org"
         },
         {
            "name":"lyon",
            "url":"http://lyon.craigslist.org"
         },
         {
            "name":"marseille",
            "url":"http://marseilles.craigslist.org"
         },
         {
            "name":"montpellier",
            "url":"http://montpellier.craigslist.org"
         },
         {
            "name":"nice / cote d'azur",
            "url":"http://cotedazur.craigslist.org"
         },
         {
            "name":"normandy",
            "url":"http://rouen.craigslist.org"
         },
         {
            "name":"paris",
            "url":"http://paris.craigslist.org"
         },
         {
            "name":"strasbourg",
            "url":"http://strasbourg.craigslist.org"
         },
         {
            "name":"toulouse",
            "url":"http://toulouse.craigslist.org"
         }
      ]
   },
   {
      "name":"Germany",
      "records":[
         {
            "name":"berlin",
            "url":"http://berlin.craigslist.de"
         },
         {
            "name":"bremen",
            "url":"http://bremen.craigslist.de"
         },
         {
            "name":"cologne",
            "url":"http://cologne.craigslist.de"
         },
         {
            "name":"dresden",
            "url":"http://dresden.craigslist.de"
         },
         {
            "name":"dusseldorf",
            "url":"http://dusseldorf.craigslist.de"
         },
         {
            "name":"essen / ruhr",
            "url":"http://essen.craigslist.de"
         },
         {
            "name":"frankfurt",
            "url":"http://frankfurt.craigslist.de"
         },
         {
            "name":"hamburg",
            "url":"http://hamburg.craigslist.de"
         },
         {
            "name":"hannover",
            "url":"http://hannover.craigslist.de"
         },
         {
            "name":"heidelberg",
            "url":"http://heidelberg.craigslist.de"
         },
         {
            "name":"kaiserslautern",
            "url":"http://kaiserslautern.craigslist.de"
         },
         {
            "name":"leipzig",
            "url":"http://leipzig.craigslist.de"
         },
         {
            "name":"munich",
            "url":"http://munich.craigslist.de"
         },
         {
            "name":"nuremberg",
            "url":"http://nuremberg.craigslist.de"
         },
         {
            "name":"stuttgart",
            "url":"http://stuttgart.craigslist.de"
         }
      ]
   },
   {
      "name":"Greece",
      "records":[
         {
            "name":"greece",
            "url":"http://athens.craigslist.gr"
         }
      ]
   },
   {
      "name":"Hungary",
      "records":[
         {
            "name":"budapest",
            "url":"http://budapest.craigslist.org"
         }
      ]
   },
   {
      "name":"Iceland",
      "records":[
         {
            "name":"reykjavik",
            "url":"http://reykjavik.craigslist.org"
         }
      ]
   },
   {
      "name":"Ireland",
      "records":[
         {
            "name":"dublin",
            "url":"http://dublin.craigslist.org"
         }
      ]
   },
   {
      "name":"Italy",
      "records":[
         {
            "name":"bologna",
            "url":"http://bologna.craigslist.it"
         },
         {
            "name":"florence / tuscany",
            "url":"http://florence.craigslist.it"
         },
         {
            "name":"genoa",
            "url":"http://genoa.craigslist.it"
         },
         {
            "name":"milan",
            "url":"http://milan.craigslist.it"
         },
         {
            "name":"napoli / campania",
            "url":"http://naples.craigslist.it"
         },
         {
            "name":"perugia",
            "url":"http://perugia.craigslist.it"
         },
         {
            "name":"rome",
            "url":"http://rome.craigslist.it"
         },
         {
            "name":"sardinia",
            "url":"http://sardinia.craigslist.it"
         },
         {
            "name":"sicilia",
            "url":"http://sicily.craigslist.it"
         },
         {
            "name":"torino",
            "url":"http://torino.craigslist.it"
         },
         {
            "name":"venice / veneto",
            "url":"http://venice.craigslist.it"
         }
      ]
   },
   {
      "name":"Luxembourg",
      "records":[
         {
            "name":"luxembourg",
            "url":"http://luxembourg.craigslist.org"
         }
      ]
   },
   {
      "name":"Netherlands",
      "records":[
         {
            "name":"amsterdam / randstad",
            "url":"http://amsterdam.craigslist.org"
         }
      ]
   },
   {
      "name":"Norway",
      "records":[
         {
            "name":"norway",
            "url":"http://oslo.craigslist.org"
         }
      ]
   },
   {
      "name":"Poland",
      "records":[
         {
            "name":"poland",
            "url":"http://warsaw.craigslist.pl"
         }
      ]
   },
   {
      "name":"Portugal",
      "records":[
         {
            "name":"faro / algarve",
            "url":"http://faro.craigslist.pt"
         },
         {
            "name":"lisbon",
            "url":"http://lisbon.craigslist.pt"
         },
         {
            "name":"porto",
            "url":"http://porto.craigslist.pt"
         }
      ]
   },
   {
      "name":"Romania",
      "records":[
         {
            "name":"romania",
            "url":"http://bucharest.craigslist.org"
         }
      ]
   },
   {
      "name":"Russian Federation",
      "records":[
         {
            "name":"moscow",
            "url":"http://moscow.craigslist.org"
         },
         {
            "name":"st petersburg",
            "url":"http://stpetersburg.craigslist.org"
         }
      ]
   },
   {
      "name":"Spain",
      "records":[
         {
            "name":"alicante",
            "url":"http://alicante.craigslist.es"
         },
         {
            "name":"baleares",
            "url":"http://baleares.craigslist.es"
         },
         {
            "name":"barcelona",
            "url":"http://barcelona.craigslist.es"
         },
         {
            "name":"bilbao",
            "url":"http://bilbao.craigslist.es"
         },
         {
            "name":"cadiz",
            "url":"http://cadiz.craigslist.es"
         },
         {
            "name":"canarias",
            "url":"http://canarias.craigslist.es"
         },
         {
            "name":"granada",
            "url":"http://granada.craigslist.es"
         },
         {
            "name":"madrid",
            "url":"http://madrid.craigslist.es"
         },
         {
            "name":"malaga",
            "url":"http://malaga.craigslist.es"
         },
         {
            "name":"sevilla",
            "url":"http://sevilla.craigslist.es"
         },
         {
            "name":"valencia",
            "url":"http://valencia.craigslist.es"
         }
      ]
   },
   {
      "name":"Sweden",
      "records":[
         {
            "name":"sweden",
            "url":"http://stockholm.craigslist.se"
         }
      ]
   },
   {
      "name":"Switzerland",
      "records":[
         {
            "name":"basel",
            "url":"http://basel.craigslist.ch"
         },
         {
            "name":"bern",
            "url":"http://bern.craigslist.ch"
         },
         {
            "name":"geneva",
            "url":"http://geneva.craigslist.ch"
         },
         {
            "name":"lausanne",
            "url":"http://lausanne.craigslist.ch"
         },
         {
            "name":"zurich",
            "url":"http://zurich.craigslist.ch"
         }
      ]
   },
   {
      "name":"Turkey",
      "records":[
         {
            "name":"turkey",
            "url":"http://istanbul.craigslist.com.tr"
         }
      ]
   },
   {
      "name":"Ukraine",
      "records":[
         {
            "name":"ukraine",
            "url":"http://ukraine.craigslist.org"
         }
      ]
   },
   {
      "name":"United Kingdom",
      "records":[
         {
            "name":"aberdeen",
            "url":"http://aberdeen.craigslist.co.uk"
         },
         {
            "name":"bath",
            "url":"http://bath.craigslist.co.uk"
         },
         {
            "name":"belfast",
            "url":"http://belfast.craigslist.co.uk"
         },
         {
            "name":"birmingham / west mids",
            "url":"http://birmingham.craigslist.co.uk"
         },
         {
            "name":"brighton",
            "url":"http://brighton.craigslist.co.uk"
         },
         {
            "name":"bristol",
            "url":"http://bristol.craigslist.co.uk"
         },
         {
            "name":"cambridge, UK",
            "url":"http://cambridge.craigslist.co.uk"
         },
         {
            "name":"cardiff / wales",
            "url":"http://cardiff.craigslist.co.uk"
         },
         {
            "name":"coventry",
            "url":"http://coventry.craigslist.co.uk"
         },
         {
            "name":"derby",
            "url":"http://derby.craigslist.co.uk"
         },
         {
            "name":"devon & cornwall",
            "url":"http://devon.craigslist.co.uk"
         },
         {
            "name":"dundee",
            "url":"http://dundee.craigslist.co.uk"
         },
         {
            "name":"east anglia",
            "url":"http://norwich.craigslist.co.uk"
         },
         {
            "name":"east midlands",
            "url":"http://eastmids.craigslist.co.uk"
         },
         {
            "name":"edinburgh",
            "url":"http://edinburgh.craigslist.co.uk"
         },
         {
            "name":"essex",
            "url":"http://essex.craigslist.co.uk"
         },
         {
            "name":"glasgow",
            "url":"http://glasgow.craigslist.co.uk"
         },
         {
            "name":"hampshire",
            "url":"http://hampshire.craigslist.co.uk"
         },
         {
            "name":"kent",
            "url":"http://kent.craigslist.co.uk"
         },
         {
            "name":"leeds",
            "url":"http://leeds.craigslist.co.uk"
         },
         {
            "name":"liverpool",
            "url":"http://liverpool.craigslist.co.uk"
         },
         {
            "name":"london",
            "url":"http://london.craigslist.co.uk"
         },
         {
            "name":"manchester",
            "url":"http://manchester.craigslist.co.uk"
         },
         {
            "name":"newcastle / NE england",
            "url":"http://newcastle.craigslist.co.uk"
         },
         {
            "name":"nottingham",
            "url":"http://nottingham.craigslist.co.uk"
         },
         {
            "name":"oxford",
            "url":"http://oxford.craigslist.co.uk"
         },
         {
            "name":"sheffield",
            "url":"http://sheffield.craigslist.co.uk"
         }
      ]
   },
   {
      "name":"",
      "records":[
         {
            "name":"guam-micronesia",
            "url":"http://micronesia.craigslist.org"
         }
      ]
   },
   {
      "name":"Bangladesh",
      "records":[
         {
            "name":"bangladesh",
            "url":"http://bangladesh.craigslist.org"
         }
      ]
   },
   {
      "name":"China",
      "records":[
         {
            "name":"beijing",
            "url":"http://beijing.craigslist.com.cn"
         },
         {
            "name":"chengdu",
            "url":"http://chengdu.craigslist.com.cn"
         },
         {
            "name":"chongqing",
            "url":"http://chongqing.craigslist.com.cn"
         },
         {
            "name":"dalian",
            "url":"http://dalian.craigslist.com.cn"
         },
         {
            "name":"guangzhou",
            "url":"http://guangzhou.craigslist.com.cn"
         },
         {
            "name":"hangzhou",
            "url":"http://hangzhou.craigslist.com.cn"
         },
         {
            "name":"nanjing",
            "url":"http://nanjing.craigslist.com.cn"
         },
         {
            "name":"shanghai",
            "url":"http://shanghai.craigslist.com.cn"
         },
         {
            "name":"shenyang",
            "url":"http://shenyang.craigslist.com.cn"
         },
         {
            "name":"shenzhen",
            "url":"http://shenzhen.craigslist.com.cn"
         },
         {
            "name":"wuhan",
            "url":"http://wuhan.craigslist.com.cn"
         },
         {
            "name":"xi'an",
            "url":"http://xian.craigslist.com.cn"
         }
      ]
   },
   {
      "name":"Hong Kong",
      "records":[
         {
            "name":"hong kong",
            "url":"http://hongkong.craigslist.hk"
         }
      ]
   },
   {
      "name":"India",
      "records":[
         {
            "name":"ahmedabad",
            "url":"http://ahmedabad.craigslist.co.in"
         },
         {
            "name":"bangalore",
            "url":"http://bangalore.craigslist.co.in"
         },
         {
            "name":"bhubaneswar",
            "url":"http://bhubaneswar.craigslist.co.in"
         },
         {
            "name":"chandigarh",
            "url":"http://chandigarh.craigslist.co.in"
         },
         {
            "name":"chennai (madras)",
            "url":"http://chennai.craigslist.co.in"
         },
         {
            "name":"delhi",
            "url":"http://delhi.craigslist.co.in"
         },
         {
            "name":"goa",
            "url":"http://goa.craigslist.co.in"
         },
         {
            "name":"hyderabad",
            "url":"http://hyderabad.craigslist.co.in"
         },
         {
            "name":"indore",
            "url":"http://indore.craigslist.co.in"
         },
         {
            "name":"jaipur",
            "url":"http://jaipur.craigslist.co.in"
         },
         {
            "name":"kerala",
            "url":"http://kerala.craigslist.co.in"
         },
         {
            "name":"kolkata (calcutta)",
            "url":"http://kolkata.craigslist.co.in"
         },
         {
            "name":"lucknow",
            "url":"http://lucknow.craigslist.co.in"
         },
         {
            "name":"mumbai",
            "url":"http://mumbai.craigslist.co.in"
         },
         {
            "name":"pune",
            "url":"http://pune.craigslist.co.in"
         },
         {
            "name":"surat surat",
            "url":"http://surat.craigslist.co.in"
         }
      ]
   },
   {
      "name":"Indonesia",
      "records":[
         {
            "name":"indonesia",
            "url":"http://jakarta.craigslist.org"
         }
      ]
   },
   {
      "name":"Iran",
      "records":[
         {
            "name":"iran",
            "url":"http://tehran.craigslist.org"
         }
      ]
   },
   {
      "name":"Iraq",
      "records":[
         {
            "name":"iraq",
            "url":"http://baghdad.craigslist.org"
         }
      ]
   },
   {
      "name":"Israel and Palestine",
      "records":[
         {
            "name":"haifa",
            "url":"http://haifa.craigslist.org"
         },
         {
            "name":"jerusalem",
            "url":"http://jerusalem.craigslist.org"
         },
         {
            "name":"tel aviv",
            "url":"http://telaviv.craigslist.org"
         },
         {
            "name":"west bank",
            "url":"http://ramallah.craigslist.org"
         }
      ]
   },
   {
      "name":"Japan",
      "records":[
         {
            "name":"fukuoka",
            "url":"http://fukuoka.craigslist.jp"
         },
         {
            "name":"hiroshima",
            "url":"http://hiroshima.craigslist.jp"
         },
         {
            "name":"nagoya",
            "url":"http://nagoya.craigslist.jp"
         },
         {
            "name":"okinawa",
            "url":"http://okinawa.craigslist.jp"
         },
         {
            "name":"osaka-kobe-kyoto",
            "url":"http://osaka.craigslist.jp"
         },
         {
            "name":"sapporo",
            "url":"http://sapporo.craigslist.jp"
         },
         {
            "name":"sendai",
            "url":"http://sendai.craigslist.jp"
         },
         {
            "name":"tokyo",
            "url":"http://tokyo.craigslist.jp"
         }
      ]
   },
   {
      "name":"Korea",
      "records":[
         {
            "name":"seoul",
            "url":"http://seoul.craigslist.co.kr"
         }
      ]
   },
   {
      "name":"Kuwait",
      "records":[
         {
            "name":"kuwait",
            "url":"http://kuwait.craigslist.org"
         }
      ]
   },
   {
      "name":"Lebanon",
      "records":[
         {
            "name":"beirut, lebanon",
            "url":"http://beirut.craigslist.org"
         }
      ]
   },
   {
      "name":"Malaysia",
      "records":[
         {
            "name":"malaysia",
            "url":"http://malaysia.craigslist.org"
         }
      ]
   },
   {
      "name":"Pakistan",
      "records":[
         {
            "name":"pakistan",
            "url":"http://pakistan.craigslist.org"
         }
      ]
   },
   {
      "name":"Philippines",
      "records":[
         {
            "name":"bacolod",
            "url":"http://bacolod.craigslist.com.ph"
         },
         {
            "name":"bicol region",
            "url":"http://naga.craigslist.com.ph"
         },
         {
            "name":"cagayan de oro",
            "url":"http://cdo.craigslist.com.ph"
         },
         {
            "name":"cebu",
            "url":"http://cebu.craigslist.com.ph"
         },
         {
            "name":"davao city",
            "url":"http://davaocity.craigslist.com.ph"
         },
         {
            "name":"iloilo",
            "url":"http://iloilo.craigslist.com.ph"
         },
         {
            "name":"manila",
            "url":"http://manila.craigslist.com.ph"
         },
         {
            "name":"pampanga",
            "url":"http://pampanga.craigslist.com.ph"
         },
         {
            "name":"zamboanga",
            "url":"http://zamboanga.craigslist.com.ph"
         }
      ]
   },
   {
      "name":"Singapore",
      "records":[
         {
            "name":"singapore",
            "url":"http://singapore.craigslist.com.sg"
         }
      ]
   },
   {
      "name":"Taiwan",
      "records":[
         {
            "name":"taiwan",
            "url":"http://taipei.craigslist.com.tw"
         }
      ]
   },
   {
      "name":"Thailand",
      "records":[
         {
            "name":"thailand",
            "url":"http://bangkok.craigslist.co.th"
         }
      ]
   },
   {
      "name":"United Arab Emirates",
      "records":[
         {
            "name":"united arab emirates",
            "url":"http://dubai.craigslist.org"
         }
      ]
   },
   {
      "name":"Vietnam",
      "records":[
         {
            "name":"vietnam",
            "url":"http://vietnam.craigslist.org"
         }
      ]
   },
   {
      "name":"Australia",
      "records":[
         {
            "name":"adelaide",
            "url":"http://adelaide.craigslist.com.au"
         },
         {
            "name":"brisbane",
            "url":"http://brisbane.craigslist.com.au"
         },
         {
            "name":"cairns",
            "url":"http://cairns.craigslist.com.au"
         },
         {
            "name":"canberra",
            "url":"http://canberra.craigslist.com.au"
         },
         {
            "name":"darwin",
            "url":"http://darwin.craigslist.com.au"
         },
         {
            "name":"gold coast",
            "url":"http://goldcoast.craigslist.com.au"
         },
         {
            "name":"melbourne",
            "url":"http://melbourne.craigslist.com.au"
         },
         {
            "name":"newcastle, NSW",
            "url":"http://ntl.craigslist.com.au"
         },
         {
            "name":"perth",
            "url":"http://perth.craigslist.com.au"
         },
         {
            "name":"sydney",
            "url":"http://sydney.craigslist.com.au"
         },
         {
            "name":"tasmania",
            "url":"http://hobart.craigslist.com.au"
         },
         {
            "name":"wollongong",
            "url":"http://wollongong.craigslist.com.au"
         }
      ]
   },
   {
      "name":"New Zealand",
      "records":[
         {
            "name":"auckland",
            "url":"http://auckland.craigslist.org"
         },
         {
            "name":"christchurch",
            "url":"http://christchurch.craigslist.org"
         },
         {
            "name":"dunedin",
            "url":"http://dunedin.craigslist.co.nz"
         },
         {
            "name":"wellington",
            "url":"http://wellington.craigslist.org"
         }
      ]
   },
   {
      "name":"",
      "records":[
         {
            "name":"caribbean islands",
            "url":"http://caribbean.craigslist.org"
         }
      ]
   },
   {
      "name":"Argentina",
      "records":[
         {
            "name":"buenos aires",
            "url":"http://buenosaires.craigslist.org"
         }
      ]
   },
   {
      "name":"Bolivia",
      "records":[
         {
            "name":"bolivia",
            "url":"http://lapaz.craigslist.org"
         }
      ]
   },
   {
      "name":"Brazil",
      "records":[
         {
            "name":"belo horizonte",
            "url":"http://belohorizonte.craigslist.org"
         },
         {
            "name":"brasilia",
            "url":"http://brasilia.craigslist.org"
         },
         {
            "name":"curitiba",
            "url":"http://curitiba.craigslist.org"
         },
         {
            "name":"fortaleza",
            "url":"http://fortaleza.craigslist.org"
         },
         {
            "name":"porto alegre",
            "url":"http://portoalegre.craigslist.org"
         },
         {
            "name":"recife",
            "url":"http://recife.craigslist.org"
         },
         {
            "name":"rio de janeiro",
            "url":"http://rio.craigslist.org"
         },
         {
            "name":"salvador, bahia",
            "url":"http://salvador.craigslist.org"
         },
         {
            "name":"sao paulo",
            "url":"http://saopaulo.craigslist.org"
         }
      ]
   },
   {
      "name":"Chile",
      "records":[
         {
            "name":"chile",
            "url":"http://santiago.craigslist.org"
         }
      ]
   },
   {
      "name":"Colombia",
      "records":[
         {
            "name":"colombia",
            "url":"http://colombia.craigslist.org"
         }
      ]
   },
   {
      "name":"Costa Rica",
      "records":[
         {
            "name":"costa rica",
            "url":"http://costarica.craigslist.org"
         }
      ]
   },
   {
      "name":"Dominican Republic",
      "records":[
         {
            "name":"dominican republic",
            "url":"http://santodomingo.craigslist.org"
         }
      ]
   },
   {
      "name":"Ecuador",
      "records":[
         {
            "name":"ecuador",
            "url":"http://quito.craigslist.org"
         }
      ]
   },
   {
      "name":"El Salvador",
      "records":[
         {
            "name":"el salvador",
            "url":"http://elsalvador.craigslist.org"
         }
      ]
   },
   {
      "name":"Guatemala",
      "records":[
         {
            "name":"guatemala",
            "url":"http://guatemala.craigslist.org"
         }
      ]
   },
   {
      "name":"Mexico",
      "records":[
         {
            "name":"acapulco",
            "url":"http://acapulco.craigslist.com.mx"
         },
         {
            "name":"baja california sur",
            "url":"http://bajasur.craigslist.com.mx"
         },
         {
            "name":"chihuahua",
            "url":"http://chihuahua.craigslist.com.mx"
         },
         {
            "name":"ciudad juarez",
            "url":"http://juarez.craigslist.com.mx"
         },
         {
            "name":"guadalajara",
            "url":"http://guadalajara.craigslist.com.mx"
         },
         {
            "name":"guanajuato",
            "url":"http://guanajuato.craigslist.com.mx"
         },
         {
            "name":"hermosillo",
            "url":"http://hermosillo.craigslist.com.mx"
         },
         {
            "name":"mazatlan",
            "url":"http://mazatlan.craigslist.com.mx"
         },
         {
            "name":"mexico city",
            "url":"http://mexicocity.craigslist.com.mx"
         },
         {
            "name":"monterrey",
            "url":"http://monterrey.craigslist.com.mx"
         },
         {
            "name":"oaxaca",
            "url":"http://oaxaca.craigslist.com.mx"
         },
         {
            "name":"puebla",
            "url":"http://puebla.craigslist.com.mx"
         },
         {
            "name":"puerto vallarta",
            "url":"http://pv.craigslist.com.mx"
         },
         {
            "name":"tijuana",
            "url":"http://tijuana.craigslist.com.mx"
         },
         {
            "name":"veracruz",
            "url":"http://veracruz.craigslist.com.mx"
         },
         {
            "name":"yucatan",
            "url":"http://yucatan.craigslist.com.mx"
         }
      ]
   },
   {
      "name":"Nicaragua",
      "records":[
         {
            "name":"nicaragua",
            "url":"http://managua.craigslist.org"
         }
      ]
   },
   {
      "name":"Panama",
      "records":[
         {
            "name":"panama",
            "url":"http://panama.craigslist.org"
         }
      ]
   },
   {
      "name":"Peru",
      "records":[
         {
            "name":"peru",
            "url":"http://lima.craigslist.org"
         }
      ]
   },
   {
      "name":"Puerto Rico",
      "records":[
         {
            "name":"puerto rico",
            "url":"http://puertorico.craigslist.org"
         }
      ]
   },
   {
      "name":"Uruguay",
      "records":[
         {
            "name":"montevideo",
            "url":"http://montevideo.craigslist.org"
         }
      ]
   },
   {
      "name":"Venezuela",
      "records":[
         {
            "name":"venezuela",
            "url":"http://caracas.craigslist.org"
         }
      ]
   },
   {
      "name":"Virgin Islands, U.S.",
      "records":[
         {
            "name":"virgin islands",
            "url":"http://virgin.craigslist.org"
         }
      ]
   },
   {
      "name":"Egypt",
      "records":[
         {
            "name":"egypt",
            "url":"http://cairo.craigslist.org"
         }
      ]
   },
   {
      "name":"Ethiopia",
      "records":[
         {
            "name":"ethiopia",
            "url":"http://addisababa.craigslist.org"
         }
      ]
   },
   {
      "name":"Ghana",
      "records":[
         {
            "name":"ghana",
            "url":"http://accra.craigslist.org"
         }
      ]
   },
   {
      "name":"Kenya",
      "records":[
         {
            "name":"kenya",
            "url":"http://kenya.craigslist.org"
         }
      ]
   },
   {
      "name":"Morocco",
      "records":[
         {
            "name":"morocco",
            "url":"http://casablanca.craigslist.org"
         }
      ]
   },
   {
      "name":"South Africa",
      "records":[
         {
            "name":"cape town",
            "url":"http://capetown.craigslist.co.za"
         },
         {
            "name":"durban",
            "url":"http://durban.craigslist.co.za"
         },
         {
            "name":"johannesburg",
            "url":"http://johannesburg.craigslist.co.za"
         },
         {
            "name":"pretoria",
            "url":"http://pretoria.craigslist.co.za"
         }
      ]
   },
   {
      "name":"Tunisia",
      "records":[
         {
            "name":"tunisia",
            "url":"http://tunis.craigslist.org"
         }
      ]
   }
];